version: '3.8'

services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: messenger-db
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
  app:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=messenger-db
      - POSTGRES_HOST=postgresdb
volumes: 
  db: